# Generated by Django 4.1.4 on 2022-12-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Users",),
    ]
