# Generated by Django 4.0.3 on 2022-06-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='orign',
            new_name='origin',
        ),
    ]
