# Generated by Django 4.1.4 on 2022-12-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0009_userspasswordf"),
    ]

    operations = [
        migrations.DeleteModel(name="UsersPasswordf",),
        migrations.AddField(
            model_name="passenger",
            name="temp",
            field=models.CharField(default="", max_length=64),
        ),
    ]
