# Generated by Django 4.1.4 on 2022-12-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0011_remove_passenger_public"),
    ]

    operations = [
        migrations.RemoveField(model_name="passenger", name="temp",),
        migrations.AddField(
            model_name="passenger",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
